// Auto-generated by LibreLane
module self_diagnosing_fir(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[3:0] x,
  input[3:0] h0,
  input[3:0] h1,
  input[3:0] h2,
  input[3:0] h3,
  input rst,
  input clk,
  input start_diag,
  output[9:0] y,
  output fault_detected,
  output[1:0] fault_location,
  output[2:0] fault_bit,
  output fault_type,
  output[3:0] fault_vector,
  output diag_busy,
  output diag_done
);
endmodule
